In [1]:
import numpy as np

In [ ]:
np.random.random()

array([0.3101464 , 0.32408148, 0.0607731 , 0.15249211, 0.53358874,
       0.58185194, 0.56750431, 0.75506703, 0.67565762, 0.50104829])

In [7]:
team1=np.random.randint(0,36,20)
team1

array([24,  4,  9,  3, 24, 19, 25, 20, 27, 20, 21, 26, 17, 26, 10,  1, 15,
       35,  6, 11], dtype=int32)

In [9]:
np.random.randint(0,36,(4,3))

array([[29,  3, 16],
       [27,  7, 26],
       [ 6,  8, 12],
       [12, 24, 19]], dtype=int32)

In [18]:
np.random.seed(75)
np.random.randint(0,100,1)

array([19], dtype=int32)

In [19]:
np.random.rand()

0.7563298857816358

In [21]:
np.random.randn(10)

array([-1.37925852, -1.26922007,  2.98437224,  0.04038575, -0.67221661,
        0.38703737,  2.39680022,  0.68111417,  1.4500866 , -2.09265058])

In [22]:
dice=np.arange(1,7)

In [23]:
np.random.choice(dice,1)

array([5])

In [24]:
dice

array([1, 2, 3, 4, 5, 6])

In [25]:
np.random.permutation(dice)

array([6, 1, 5, 4, 2, 3])

In [26]:
np.sin(np.radians(30))

np.float64(0.49999999999999994)

In [28]:
np.radians(np.sin(3*3.14))

np.float64(8.339082966900845e-05)